# -*- coding: utf-8 -*-
"""AULA - Linguagem de Programação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WC3Acfns2FbJU5Cr5tnqQ_0f10tSnXyi

#U1_A1
"""

#1.Nosso primeiro programa

print('Hello World')

#2.Criando Variaveis de tipos diferentes
x = 10
nome = "Anderson"
nota = 8.75
fez_inscricao = True

print (nome)
print (nota)
print (fez_inscricao)

print (type(x))
print (type(nome))
print (type(nota))
print (type(fez_inscricao))

nome = input ("Digite seu nome:")

print(f"Olá {nome}, Bem-vindo à disciplina de programação")

nota_1 = int(input("DIGITE A NOTA: "))
nota_2 = int(input("DIGITE A NOTA: "))
nota_3 = int(input("DIGITE A NOTA: "))
nota_4 = int(input("DIGITE A NOTA: "))

media = (nota_1+nota_2+nota_3+nota_4)/4

print (media)

if media >= 6:
    situacao = "Aprovado"
else:
    sitacao = "Reprovado"

print (situacao)

"""##U1_A2"""

print(10>5)

print(5>10)

print(7==7)

print(7!=7)

#aguardando informações
idade = 20
e_maior_de_idade = idade >= 18
print (e_maior_de_idade)

print(True and True)

print(True or False)

idade = int(input("Digite sua idade: "))
if idade < 18:
  print("Menor de Idade")
elif idade >= 18 and idade < 65:
    print("Adulto")
else:
  print("Idoso")

idade = int(input("Digite sua idade: "))
if idade < 12:
  print("Recomendamos o filme infantil 1")
elif idade >= 12 and idade < 18:
    print("Recomendamos o filme 2")
else:
  print("Recomendamos o filme 3")

quantidade_de_ingresso = 10
if quantidade_de_ingresso > 0:
    print("Ingressos disponiveis. Divirta-se no cinema.")
else:
    print("Desculpe, todos os ingressos foram vendidos.")

idade = int(input("Digite sua idade: "))
quantidade_de_ingresso = 10

if idade < 12:
  print("Recomendamos o filme 1")
  if quantidade_de_ingresso > 0:
    print("Ingressos disponiveis. Divirta-se no cinema.")
  else:
    print("Desculpe, todos os ingressos foram vendidos.")

elif idade >= 12 and idade < 18:
    print("Recomendamos o filme 2")
    if quantidade_de_ingresso > 0:
      print("Ingressos disponiveis. Divirta-se no cinema.")
    else:
      print("Desculpe, todos os ingressos foram vendidos.")

else:
    print("Recomendamos o filme 3")
    if quantidade_de_ingresso > 0:
      print("Ingressos disponiveis. Divirta-se no cinema.")
    else:
      print("Desculpe, todos os ingressos foram vendidos.")

"""##U1_A3"""

numeros = [1, 2, 3, 4, 5]

for numeros in numeros:
  print("%f Camisetas: {numeros}")

print(type(numeros))

numero = int(input("Digite um número(ou 0 para sair):"))

while numeros !=0:
  if numero % 2 == 0:
    print("O número é par.")
  else:
      print("O número é ímpar.")

for x in range(1, 15, 3):
  print(x)

filmes = ["Filme 1", "Filme 2", "Filme 3", "Filme 4", "Filme 5"]
print("Bem Vindo a classificação do filme")
print("Você tem 5 filmes para classificar")
print("Digite '0' a qualquer momento para sair. \n")
for filme in filmes:
    classificacao = input(f"Como você classifica '{filme}' de 1 a 5(ou 0 para sair.): ")

    if classificacao == '0':
      print("Que pena")
      break

      classificacao = int(classificacao)
      if classificacao <1 or classuficacao >5:
        print("Nota invalida")
      else:
          print(f"Você classificou '{filmes}' com a '{classificacao}' estrelas. \n ")
          print("Obrigado!")

"""##U1_A4"""

numero = [1, 2, 3, 4, 5]

comprimento = len(numero)

comprimento

range(5)

def soma(a,b):
  resultado = a + b
  return resultado

resultado_soma = soma(5,6)

print(resultado_soma)

def e_par(numero):
  if numero % 2 ==0:
    return True
  else:
    return False

numero = 54124
teste = e_par(numero)

print(teste)

media = 8.23231415
arredondar_media = lambda media: round(media, 2)

media_arkedondada = arredondar_media(media)
print(arredondar_media)

media

"""##Encerramento"""

#Funções definidas pelo usario
def calcular_desconto(valor, percentual):
  """Calcula o valor final aplicando um desconto percentual."""
  if percentual < 0 or percentual > 100:
    return None #marcacao invalida
  desconto = valor * (percentual/100)
  return valor - desconto

def registrar_venda(produto, valor_final):
  """Imprime o registro de uma venda, """
  print(f">> Venda registrada: {produto} por R$ {valor_final :.2f}")

  #funcao lambda para arredondar

arredondar = lambda v: round(v,2)

#Variáveis principais do PDV
total_vendas = 0
qtd_vendas = 0

#Loop principal do caixa. MINHALOJAPDV
while True:
  print("\n ----- minha loja - pdv ----- ")
  print("1 - Regristrar Venda")
  print("2 - Ver relatorio do dia")
  print("3 - Encerrar Caixa")

  opcao = input("Escolha uma opção: ")

  if opcao == '0':
    print("Encerrando o caixa. Até Amanhã")
    break

  elif opcao == "1":
    produto = input("Nome do Produto: ")
    valor = float(input("Valor do Produto: R$ "))
    percentual = float(input("Desconto (%): "))

    valor_final = calcular_desconto(valor,percentual)

    if valor_final is None:
      print("Desconto Invalido! Use um valor entre 0 e 100")
    else:
      valor_final = arredondar(valor_final)
      registrar_venda(produto, valor_final)
      total_vendas = total_vendas + valor_final
      qtd_vendas = qtd_vendas + 1

  elif opcao == "2":
    print(f"\nVendas hoje: {qtd_vendas}")
    print(f"Total faturado: R$ {arredondar(total_vendas)}")

  else:
    print("Opcão Inválida. Tente de novo.")

"""##U2_A1"""

texto = "Explorando a diversidade de linguagens de programação com Python"

print(f"Tamanho do texto = {len(texto)}")

print(f"Quantidade de 'e' no texto = {texto.count('e')}")

print(f"As 5 primeiras letras são: {texto[:5]}")

cores = ['v', 'ver', 'az', 'am']

for cor in cores:
  print(f'Posição = {cores.index(cor)}, cor = {cor}')

linguagens = ["Python", "Java", "Javascript", "C#"]

print("Antes da listcom =", linguagens)

linguagens = [item.lower() for item in linguagens]
print("\nDepois da listcomp=", linguagens)

vogais = ('a', 'e', 'i', 'o', 'u')

print(f"Tipo de objeto vogais = [type(vogais)]")

for p, z in enumerate(vogais):
    print(f"Posição = {p}, valor = {z}")

vogais = ('a', 'e', 'i', 'o', 'u', 'z')

print(vogais)

cores = ("azul", "verde")

outra = cores

cores = ("vermelho", "amarelo")

print(outra)
print(cores)

cores = ("vermelho", "amarelo")

print(cores)

convidados = ("alice", "rodrigo", "carol", "felipe")
confirmados = ["alice", "rodrigo"]

print("Convidados que ainda não confimaram: ")
for convidado in convidados:
  if convidado not in confirmados:
    print(f"- {convidado}")

"""##U2_A2"""

meu_conjunto = set()

meu_conjunto.add(10)

meu_conjunto.add(20)
meu_conjunto.add(30)

meu_conjunto.add(10)

meu_conjunto.remove(20)

meu_conjunto

elemento = 20
if elemento in meu_conjunto:
  print(f"O elemento {elemento} está no conjunto.")
else:
  print(f"O elemento {elemento} não está no conjunto.")

numeros_com_repeticao = [1,2,2,3,3,3,4,4,4,4]

unicos = set(numeros_com_repeticao)

numeros_com_repeticao

unicos

dici_1 = {}

dici_1['nome'] = "Maria"
dici_1['idade'] = 25

dici_1

dici_2 = {'nome': 'Maria', 'idade': 25}

dici_2

dici_3 = dict(nome = 'Maria', idade = 25)

dici_3

dici_4 = dict(zip(['nome', 'idade'], ['Maria', 25]))

dici_4

#Acessando e alterando valores num dicionario
produto = {'nome': 'Notebook', 'preco': 3500.00, 'estoque': 12}

print("Nome:", produto['nome'])
print("Preço:", produto['preco'])

#Alterando o estoque
produto['estoque'] = 10
#Adciionando uma chave nova
produto['categoria'] = 'Informática'

print(produto)

#Numpy - Importando e criando um array
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print("Array original:")
print(my_array)

#NumPy - operações em massa
squared_array = my_array **2          #cada elemento ao quadrado
sum_of_elements = np.sum(my_array)    #soma de todos os elementos

print("\nArray ao quadrado:")
print(squared_array)
print('\nSoma dos elementos:')
print(sum_of_elements)

#Acessando um elemnto por índice
print("\nElemento no índice 2:", my_array[2])

#Vamos exercitar - o evento científico
import numpy as np

#Cada participante é um dicionário (mapping)
participantes = [
    {"nome": "Alice", "localizacao": "EUA", "afiliacao": "Universidade A",
     "interesses": ["Fisica", "Astronomia"]},
    {"nome": "Bob", "localizacao": "Brasil", "afiliacao": "Instituto B",
    "interesses": ["Biologia", "Astronomia"]},
    {"nome": "Charlie", "localizacao": "Índia", "afiliacao": "Instituto C",
     "interesses": ["Química", "Engenharia"]},
]

#Set - regiões dos participantes (sem duploicar)
regioes = set(p["localizacao"] for p in participantes)

#Dict - agrupando nomes por afiliação
afiliacoes = {}
for p in participantes:
  aff = p["afiliacao"]
  if aff not in afiliacoes:
    afiliacoes[aff] = []
    afiliacoes[aff].append(p["nome"])

#Numpy - área de interesse mais popular
areas = np.array([i for p in participantes for i in p["interesses"]])
unicos, contagem = np.unique(areas, return_counts=True)
mais_popular = unicos[np.argmax(contagem)] #argmax = argumento maximo? basicamente ele conta a quantidade e seleciona o maior numero

#Resultados
print("Regiões dos participantes:", regioes)
print("Afiliações dos participantes:")
for aff, nomes in afiliacoes.items():
  print(f" - {aff}: {', '.join(nomes)}")
print("Área de interesse mais popular:", mais_popular)

"""##U2_A3"""

class Pessoa:
  def __init__(self, nome, idade, genero):
    self.nome = nome
    self.idade = idade
    self.genero = genero

  def cumprimentar(self):
    return f"Olá, meu nome é {self.nome}."

  def aniversario(self):
    self.idade += 1

pessoa1 = Pessoa("João", 30, "Masculino")

print(pessoa1.cumprimentar())
print(f"Idade: {pessoa1.idade}")

#Chama o método aniversario para aumentar a idade
pessoa1.aniversario()
print(f"Nova idade: {pessoa1.idade}")

#Herança - Classe-pai Animal e duas classes-filhas
class Animal:
  def __init__(self, nome):
    self.nome = nome

    def fazer_barulho(self):
      pass      #método "vazio" que será sobrescrito pelas filhas

class Cachorro(Animal):
  def fazer_barulho(self):
    return "Latir"

class Gato(Animal):
  def fazer_barulho(self):
    return "Miar"

#criando e usando objetos das classes filhas
rex = Cachorro("Rex")
whiskers = Gato("Whiskers")

print(f"{rex.nome} faz: {rex.fazer_barulho()}")
print(f"{whiskers.nome} faz: {whiskers.fazer_barulho()}")

##Vamos exercitar - classe Veiculo (classe pai)
class Veiculo:
  def __init__(self, marca, modelo, ano):
    self.marca = marca
    self.modelo = modelo
    self.ano = ano
    self.velocidade = 0     ##todo veiculo começa parado

  def acelerar(self, incremento):
    self.velocidade += incremento

  def frear(self, decremento):
    self.velocidade -= decremento

  def status(self):
    return (f"Marca: {self.marca}, Modelo: {self.modelo},"
            f"Ano: {self.ano}, Velocidade: {self.velocidade} km/h")

##Classes filhas - Carro e Bicicleta
class Carro(Veiculo):
  def __init__(self, marca, modelo, ano, potencia):
    super().__init__(marca, modelo, ano)     ##super() chama o construtor da classe pai
    self.potencia = potencia

##sobrescrevendo o método acelerar
  def acelerar(self, incremento):
    self.velocidade += incremento + self.potencia

class Bicicleta(Veiculo):
  def __init__(self, marca, modelo, ano,tipo):
    super().__init__(marca, modelo, ano)
    self.tipo = tipo

##Sobrescrevendo o status para incluir o tipo
  def status(self):
    return (f"Marca: {self.marca}, Modelo: {self.modelo}, "
            f"Ano: {self.ano}, Tipo: {self.tipo}, "
            f"Velocidade: {self.velocidade} km/h")

##Testando os objetos
carro1 = Carro("Toyota", "Corolla", 2022, 150)
bicicleta1 = Bicicleta("Trek", "Mountain Bike", 2021, "MTB")

carro1.acelerar(50)
bicicleta1.acelerar(20)

print("Status do Carro:")
print(carro1.status())
print("\nStatus da Bicilceta:")
print(bicicleta1.status())

"""##U2_A4"""

##Primeira forma - import math (usa math.funcao)
import math

print(math.sqrt(25))    #raiz quadrada
print(math.log2(1024)) #logaritmo na base 2
print(math.cos(45))    #cosseno

##Segunda forma - import math as m(apelido)
import math as m

print(m.sqrt(25))
print(m.log2(1024))
print(m.cos(45))

##terceira forma - from math import(carrega só o que precisa)
from math import sqrt, log2, cos

print(sqrt(25))
print(log2(1024))
print(cos(45))

#Matplotlib - primeiro gráfico de linha
import matplotlib.pyplot as plt

#DADOS
x = [1, 2, 3, 4, 5]
y = [2, 4, 1, 3, 5]

plt.plot(x, y)

plt.xlabel('Eixo X')
plt.ylabel('Eixo Y')

plt.title('Exemplo de Grafico de Linha')

import matplotlib.pyplot as plt


# Dados de exemplo

meses = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio']

vendas = [120, 90, 150, 80, 200]


# Criar um gráfico de barras

plt.bar(meses, vendas, color='royalblue')


# Adicionar rótulos aos eixos

plt.xlabel('Mês')

plt.ylabel('Vendas (em unidades)')


# Adicionar um título ao gráfico

plt.title('Vendas Mensais');

"""##ENCERRAMENTO U2"""

import matplotlib.pyplot as plt

class Produto:
  def __init__(self, nome, preco, categoria, estoque):
    self.nome = nome
    self.preco = preco
    self.categoria = categoria
    self.estoque = estoque
##Definimos como o produto aparece quando é impresso
  def __str__(self):
     return (f"{self.nome} | R$ {self.preco:.2f} | "
             f"Categoria: {self.categoria} | Estoque: {self.estoque}" )

catologo = []
categorias = []

def adicionar_produto(nome, preco, categoria, estoque):
  novo_produto = Produto(nome, preco, categoria, estoque)
  catologo.append(novo_produto)
  categorias.append(categoria)
  print(f"Produto {nome} adicionado ao catálogo")

def remover_produto(nome, preco, categoria, estoque):
  # Percorre os produtos do catálogo
  for produto in catologo:
    # Se o nome do produto bater com o que foi pedido
    if produto.nome == nome:
      catologo.remove(produto)  # Remove o objeto da lista
      print(f"Produto '{nome}' removido do catálogo.")
      return
  print(f"Produto '{nome}' não foi encontrado.")

def listar_catalogo():
  print("\n---Catálogo da MinhaLoja---")
  for produto in catologo:
    print(produto)

##Cadastrar Produtos
adicionar_produto("Notebook",       3500.00, "Informática",     12)
adicionar_produto("Smartphone",     2200.00, "Informática",     18)
adicionar_produto("Cafeteira",      3500.00, "Eletrodoméstico",    7)
adicionar_produto("Geladeira",      2900.00, "Eletrodoméstico",    4)
adicionar_produto("Fone Bluetooth", 180.00 , "Acessório",       30)

listar_catalogo()

adicionar_produto("Sofá", 1000.00 , "Móveis",       30)

##Grafico por categoria
categorias_unicas = list(set(categorias))
categorias_unicas.sort()

##Contagem de produtos em cada categoria(list comprehension)
contagem = [categorias.count(cat) for cat in categorias_unicas]

plt.bar(categorias_unicas, contagem, color="royalblue")
plt.xlabel('Categoria')
plt.ylabel('Numero de Produtos')
plt.title('MinhaLoja - Produtos por Categoria')

remover_produto("Sofá", 1000.00 , "Móveis",       30)

listar_catalogo()

for i, valor in enumerate(contagem):
  plt.text(i, valor, str(valor), ha='center', va='bottom')

plt.grid(axis='y')
plt.show()

"""##U3_A1"""

import sqlite3

# Conectar (ou criar) o banco de dados
conn = sqlite3.connect('minhaloja.db')
cursor = conn.cursor()

create_table = """
CREATE TABLE IF NOT EXISTS Produtos (
id INTEGER PRIMARY KEY,
nome TEXT NOT NULL,
preco REAL NOT NULL,
estoque INTEGER)
"""

cursor.execute(create_table)
conn.commit()
conn.close()
print("tabela produtos criada.")

#Adicionar produto

conn = sqlite3.connect('minhaloja.db')
cursor = conn.cursor()
novo_produto = ('Camiseta', 19.99, 50)
inserir_produto = "INSERT INTO Produtos (nome, preco, estoque) VALUES (?, ?, ?)"

cursor.execute(inserir_produto, novo_produto)
conn.commit()
conn.close()

print("Produto inserido.")

#READ
conn = sqlite3.connect('minhaloja.db')
cursor = conn.cursor()

cursor.execute("SELECT * FROM Produtos")
produtos = cursor.fetchall()

for produto in produtos:
  print(produto)

  conn.close()

# UPDATE - atualizando o preço do produto com id = 1
import sqlite3

conn = sqlite3.connect('minhaloja.db')
cursor = conn.cursor()

novo_preco = 24.99
produto_id = 1

cursor.execute(
    "UPDATE Produtos SET preco = ? WHERE id = ?",
    (novo_preco, produto_id)
)
conn.commit()
conn.close()

print("Produto atualizado.")

# DELETE - excluindo o produto com id = 2
import sqlite3

conn = sqlite3.connect('minhaloja.db')
cursor = conn.cursor()

produto_id = 2

cursor.execute("DELETE FROM Produtos WHERE id = ?", (produto_id,))
conn.commit()
conn.close()

print("Produto excluído.")

# Vamos Exercitar - tabela Contatos com CRUD completo
import sqlite3

conn = sqlite3.connect('contatos.db')
cursor = conn.cursor()

#CREATE -- criar a tabela
cursor.execute("""
    CREATE TABLE IF NOT EXISTS Contatos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nome TEXT,
        email TEXT,
        telefone TEXT
        )
  """)

## Inserir vários contatos de uma vez com executemany
dados_exemplo = [
    ('João',    'joao@email.com',   '123-456-7890'),
    ('Maria',   'maria@email.com',  '987-654-3210'),
    ('Carlos',  'carlos@email.com', '555-555-5555'),
]
cursor.executemany(
    "INSERT INTO Contatos (nome, email, telefone) VALUES (?, ?, ?)",
    dados_exemplo
)
conn.commit()

#READ - listar todos os contatos
cursor.execute("SELECT * FROM Contatos")
contatos = cursor.fetchall()
print('Contatos:')
for contato in contatos:
  print(contato)

#UPDATE - atualizar telefone do contato com id = 2
cursor.execute(
    "UPDATE Contatos SET telefone = ? WHERE id = ?",
    ('999-999-9999', 2)
)
conn.commit()

## DELETE - excluir o contato com id = 1
cursor.execute("DELETE FROM Contatos WHERE id = ?", (1,))
conn.commit()

#Confirmar o estado final
cursor.execute("SELECT * FROM Contatos")
print("\nContatos após UPDATE e DELETE:")
for contato in cursor.fetchall():
  print(contato)

conn.close()

conn = sqlite3.connect('contatos.db')
cursor = conn.cursor()
cursor.execute("SELECT COUNT(DISTINCT email) FROM Contatos")
for contato in cursor.fetchall():
  print(contato[0])
conn.close()

"""##U3_A2"""

import pandas as pd
exemplo1 = [10, 20, 30, 40, 50]
print(type(exemplo1))

series1 = pd.Series(data=exemplo1)
print(type(series1))

print(series1)

exemplo2 = {'A': 100, 'B': 200, 'C': 300, 'D': 400, 'E': 500}
series2 = pd.Series(data=exemplo2)
print(series2)

## Métodos prontos da Series
print("Média:", series2.mean())
print("Soma:", series2.sum())
print("Máximo:", series2.max())
print("Mínimo:", series2.min())

import pandas as pd

url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'
dfs = pd.read_html(url)

print(type(dfs))    ##<class 'list>
print(len(dfs))     ##quantidade de tabelas encontradas

##Explorando o DataFrame(tabela de excel) resultante
df_bancos = dfs[0]

print("Dimensões (linhas, colunas):", df_bancos.shape)
print("\nTipos de cada coluna:")
print(df_bancos.dtypes)
print("\nPrimeiras 5 linhas:")
df_bancos.head()

df = pd.read_csv("ipeadata.csv")

df.head()

#Vamos exercitar - idade média dos clientes
import pandas as pd

##Dados dos clientes
dados = {
    'Nome':   ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Idade':  [25, 30, 22, 35, 28],
}

##Criar uma Series com idades indexadas pelo nome
serie_idades = pd.Series(dados['Idade'], index=dados['Nome'])

print("Série de Idades:")
print(serie_idades)

##Calcular a média de idades
media_idades = serie_idades.mean()
print(f"\nMédia de idades: {media_idades}")

##Outras estatisticas que ajudam na decisão de marketing
print(f"Idade mínima: {serie_idades.min()}")
print(f"Idade máxima: {serie_idades.max()}")

"""##U3_A3"""

import pandas as pd

## Passo 1 - leitura com read_sjon (dado real, API pública do Banco Central)
url = "https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarPeriodo(dataInicial=@dataInicial,dataFinalCotacao=@dataFinalCotacao)?@dataInicial='01-01-2025'&@dataFinalCotacao='06-01-2025'&$format=json&$select=cotacaoCompra,cotacaoVenda,dataHoraCotacao"

df = pd.read_json(url)

print(df.info())

df.head()

print(df.head())

df = pd.json_normalize(df['value'])

df.head()

df.columns = ['compra', 'venda', 'data']

df.head()

df['spread'] = df['venda'] - df['compra']
df.head()

print(df.loc[0])

print(df.loc[[0, 5, 10]])

print(df.loc [0:4, ['data', 'venda']])

caro = df[df['venda'] > 6.00]
print(f"Dias com dólar acida de R$:6,00: {len(caro)}")
print(caro)

spread_alto = df[df['spread'] > 0.0005]
print(spread_alto[['data', 'compra', 'venda', 'spread']])

import matplotlib.pyplot as plt

## Garantir que a coluna data é datatime
df['data'] = pd.to_datetime(df['data'])

## Criar o gráfico
plt.figure(figsize=(12, 5))
plt.plot(df['data'], df['venda'], color='royalblue', linewidth=2)

plt.title('Cotação do Dólar (Venda) - Jan a Jun 2025')
plt.xlabel('Data')
plt.ylabel('R$:')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""##U3_A4"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url = 'https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv'
df = pd.read_csv(url)
df_raw = pd.read_csv(url)

df.head()

df = df_raw[df_raw['state'] == 'TOTAL'].copy()

df.head()

df['date'] = pd.to_datetime(df['date'])

df.head(1)

df = df[['date', 'newCases', 'newDeaths', 'totalCases']].reset_index(drop=True)

df.head(2)

print(f"Ddos de {df['date'].min().date()} até {df['date'].max().date()}")
print(f"Total de dias registrados: {len(df)}")

fig, ax = plt.subplots(figsize=(13, 5))
ax.plot(df['date'], df['newCases'], color='steelblue', linewidth=1.5)
ax.fill_between(df['date'], df['newCases'], alpha=0.25, color='steelblue')
ax.set_title("Novos casos por dia - Brasil (pandemia completga)", fontsize=14)
ax.set_xlabel("Data")
ax.set_ylabel("Novos casos")
plt.tight_layout()
plt.show()

ondas = [
    ("1ª onda", "2020-07-15", "steelblue"),
    ("2ª onda", "2021-03-15", "tomato"),
    ("3ª onda", "2022-02-01", "steelblue")
]

ondas

fig, ax = plt.subplots(figsize=(13, 5))
ax.plot(df['date'], df['newCases'], color='gray', linewidth=1.2)
ax.fill_between(df['date'], df['newCases'], alpha=0.15, color='gray')
for nome, data, cor in ondas:
  ax.axvline(pd.to_datetime(data), color=cor, linestyle='--', linewidth=1.8, label=nome)

ax.set_title("As três ondas de COVID no Brasil")
ax.set_ylabel ("Novos casos")
ax.legend()
plt.tight_layout()
plt.show()

fig, ax1 = plt.subplots(figsize=(13, 5))

ax1.plot(df['date'], df['newCases'], color='steelblue', label='Novos casos')
ax1.set_ylabel("Novos casos", color='steelblue')

ax2 = ax1.twinx()   ##segundo eixo Y no mesmo gráfico
ax2.plot(df['date'], df['newDeaths'], color='tomato', label='Mortes', linewidth=1.5)
ax2.set_ylabel("Mortes", color='tomato')

ax1.set_title("Casos vs Mortes - por que a curva de mortes não acompanha os casos?")
fig.legend(loc='upper left', bbox_to_anchor=(0.1, 0.88))
plt.tight_layout()
plt.show()

df['mes'] = df['date'].dt.to_period('M').astype(str)

sns.set(style="whitegrid")
plt.figure(figsize=(14, 5))
sns.barplot(data=df, x='mes', y='newDeaths',
            estimator='sum', errorbar=None, palette='Reds_d')
plt.title("Total de mortes por mês - Brasil")
plt.xlabel("Mês")
plt.ylabel("Mortes no mês")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""##ENCERRAMENTO UNIDADE 3"""

import sqlite3

conn = sqlite3.connect('minhaloja.db')
cursor = conn.cursor()

cursor.execute("""
    CREATE TABLE IF NOT EXISTS vendas (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        data TEXT,
        produto TEXT,
        categoria TEXT,
        quantidade INTEGER,
        valor_unitario REAL
      )
""")

cursor.execute("DELETE FROM vendas")
conn.commit()
print("tabela vendas criada.")

##Inserir Vendas

vendas_exemplo = [
    ('2024-01-15', 'Notebook',       'Informática',      1, 3500.00),
    ('2024-01-20', 'Cafeteira',      'Eletrodoméstico',  2,  350.00),
    ('2024-01-30', 'Fone Bluetooth', 'Acessório',        4,  180.00),
    ('2024-02-05', 'Smartphone',     'Informática',      1, 2200.00),
    ('2024-02-18', 'Fone Bluetooth', 'Acessório',        3,  180.00),
    ('2024-02-25', 'Notebook',       'Informática',      2, 3500.00),
    ('2024-03-10', 'Geladeira',      'Eletrodoméstico',  1, 2900.00),
    ('2024-03-22', 'Fone Bluetooth', 'Acessório',        5,  180.00),
    ('2024-03-28', 'Cafeteira',      'Eletrodoméstico',  1,  350.00),
    ('2024-04-02', 'Smartphone',     'Informática',      2, 2200.00),
    ('2024-04-19', 'Geladeira',      'Eletrodoméstico',  1, 2900.00),
    ('2024-04-25', 'Notebook',       'Informática',      1, 3500.00),
    ('2024-05-03', 'Cafeteira',      'Eletrodoméstico',  3,  350.00),
    ('2024-05-15', 'Smartphone',     'Informática',      2, 2200.00),
    ('2024-05-28', 'Fone Bluetooth', 'Acessório',        6,  180.00),
    ('2024-06-10', 'Geladeira',      'Eletrodoméstico',  2, 2900.00),
    ('2024-06-20', 'Notebook',       'Informática',      3, 3500.00),
    ('2024-06-30', 'Smartphone',     'Informática',      1, 2200.00),
]

cursor.executemany(
    "INSERT INTO vendas (data, produto, categoria, quantidade, valor_unitario) VALUES (?, ?, ?, ?, ?)",
    vendas_exemplo
)
conn.commit()
print(f"{len(vendas_exemplo)} vendas inseridas.")

##Ler direto para DataFrame + fechar conexão
import pandas as pd

df = pd.read_sql("SELECT * FROM vendas", conn)
conn.close()

df['total'] = df['quantidade'] * df['valor_unitario']
df['data'] = pd.to_datetime(df['data'])
df['mes'] = df['data'].dt.month
df['mes_nome'] = df['data'].dt.strftime('%b')  #Jan, Fev, Mar...

print(f"Faturamento total da MinhaLoja: R$ {df['total'].sum():,.2f}")
df.head()

acima_de_1000 = df[df['total'] > 1000]

print(f"Vendas acima de R$:1.000: {len(acima_de_1000)} de {len(df)} registros\n")
print(acima_de_1000[['data', 'produto', 'quantidade', 'total']]
      .sort_values('total', ascending=False)
      .to_string(index=False))

##Painel Completo

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
meses_ordem = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
fig.suptitle('MinhaLoja v3 - Relatório de Vendas 2024', fontsize=10, fontweight='bold', y=1.01)

##Grafico 1 - Faturamento por mês (linha + pontos)
fat_mes = df.groupby('mes_nome')['total'].sum().reindex(meses_ordem)
axes[0, 0].plot(fat_mes.index, fat_mes.values, marker='o', color='steelblue', linewidth=2.5)
axes[0, 0].fill_between(fat_mes.index, fat_mes.values, alpha=0.15, color='steelblue')
axes[0, 0].set_title('Faturamento por Mês')
axes[0, 0].set_ylabel('R$')

#Gráfico 2 - Faturamento por categoria(barras horizontais - mais fácil de ler)
fat_cat = df.groupby('categoria')['total'].sum().sort_values()
axes[0, 1].barh(fat_cat.index, fat_cat.values, color=sns.color_palette('Set2', len(fat_cat)))
axes[0, 1].set_title('Faturamento por Categoria')
axes[0, 1].set_xlabel('R$')

#Gráfico 3 - Quantidade vendida por produto
qtd_prod = df.groupby('produto')['quantidade'].sum().sort_values(ascending=False)
sns.barplot(x=qtd_prod.index, y=qtd_prod.values, ax=axes[1, 0], palette='Blues_d')
axes[1, 0].set_title('Unidades Vendidas por Produto')
axes[1, 0].set_ylabel('Qtde')
axes[1, 0].set_xlabel('')

##Gráfico 4 - Pizza: partição de cada categoria no faturamento
fat_cat2 = df.groupby('categoria')['total'].sum()
axes[1, 1].pie(fat_cat2.values, labels=fat_cat2.index,
               autopct='%1.1f%%', colors=sns.color_palette('Set2', len(fat_cat2)),
               startangle=90)

ranking = (df.groupby('produto')['total']
              .sum()
              .sort_values(ascending=False)
              .reset_index())

ranking.columns = ['Produto', 'Faturamento Total']
ranking['Faturamento Total'] = ranking['Faturamento Total'].apply(lambda x: f"R$ {x:,.2f}")

print("\n🏆 Ranking de faturamento da MinhaLoja:")
print(ranking.to_string(index=False))

conn = sqlite3.connect('minhaloja.db')
cursor = conn.cursor()
fat_mes = pd.read_sql("""
    SELECT
      strftime('%m', data) AS mes_num,
      strftime('%b', data) AS mes,
      SUM(quantidade * valor_unitario) AS faturamento
    FROM vendas
    GROUP BY mes_num
    ORDER BY mes_num
""", conn)

print("Faturamento por mês:")
print(fat_mes)

ranking = pd.read_sql("""
    SELECT
      produto,
      SUM(quantidade)                   AS unidades_vendidas,
      SUM(quantidade * valor_unitario)  AS faturamento_total
    FROM vendas
    GROUP BY produto
    ORDER BY faturamento_total DESC
""", conn)

print("Ranking de produtos:")
print(ranking)

"""##U4_A1"""

##CENA 1 O QUE O CLIENTE VÊ
from IPython.display import HTML

HTML("""
  <div style="font-family: Arial; padding: 20px; background: #f8f9fa; border-radius: 8px;">
    <h2 style="color: #2c3e50;">👋 Olá, eu sou um desenvolvedor Python</h2>
    <p style="color: #555;">Esta linha foi gerada pelo Python - mas o cliente só vê o resultado.</p>
  </div>
""")

##Cena 2 portifólio

nome = "ERICSON"
cidade = "SÃO PAULO"
cargo = "Professor"
habilidades = ["PYTHON", "MATEMÁTICA", "DATA SCIENCE"]
projeto = "Sistema de vendas com banco de dados SQLITE"

skills_html = "".join([
    f'<span style ="background:#3498db; color:white; padding:4px 12px;'
    f'border-radius:20px; margin:4px; display:inline-block;">{s}</span>'
    for s in habilidades
])

portfolio = f"""
<!DOCKTYPE html>
<html>
<head>
  <style>
    body      {{  font-family: Arial, sans-serif;background: #f0f4f8;
                margin: 0; padding: 30px; }}
    .card     {{  max-width: 620px; margin: auto; background: white;
                border-radius: 12px; padding: 35px;
                box-shadow: 0 4px 16px rgba(0,0,0,0.1); }}
    header    {{  border-bottom: 3px solid #3498db; padding-bottom: 15px;
                margin-bottom: 20px; }}
    h1        {{  margin: 0; color: #2c3e50; font-size: 1.8em; }}
    .cargo    {{  color: #3498db; font-weight: bold; margin-top: 4px; }}
    .cidade   {{  color: #888; font-size: 1.1em; margin-top 25px; }}
    h2        {{  color: #2c3e50; font-size: 1.1em; margin-top: 25px; }}
    .projeto  {{  backgorund: #f8f9fa; border-left: 4px solid #3498db;
                  padding: 12px 16px; border-radius: 4px; color: #444; }}
  </style>
</head>
<body>
  <div class="card">
    <header>
      <h1>{nome}</h1>
      <p class="cargo">{cargo}</p>
      <p class="cidade">📍 {cidade}</p>
    </header>

    <h2>🛠️ Habilidades </h2>
    {skills_html}

    <h2>🚀 Projeto em Destaque</h2>
    <div class="projeto">{projeto}</div>
  </div>
</body>
</html>
"""

HTML(portfolio)

#back-end
def gerar_pagina(usuario):
    """Simula o que um servidor Flask faria ao receber uma requisição"""
    return {
        "status": 200,
        "content_type": "text/html",
        "body": f"<h1>Portfólio de {usuario['nome']}</h1>"
    }


#Dados que viriam do banco de dados (como na U3!)
usuario = {
           "nome": nome,
           "cargo": cargo,
           "cidade": cidade
}

resposta = gerar_pagina(usuario)
print(f"Status: {resposta['status']}")
print(f"Tipo: {resposta['content_type']}")
print(f"Conteúdo gerado: {resposta['body']}")

from IPython.display import HTML

html_code = """

<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Meu Perfil</title>

</head>

<body style="font-family: 'Arial', sans-serif; background-color: #f8f8f8; margin: 0; padding: 0;">


<header style="text-align: center; background-color: #3498db; color: #fff; padding: 20px;">

<h1 style="margin: 0;">Anderson Inácio Salata de Abreu</h1>

<p style="margin: 5px 0;">Desenvolvedor Web</p>

</header>


<section style="margin: 20px; text-align: center;">

<img src="content/sua_foto.jpg" alt="Sua Foto" style="border-radius: 50%; margin-bottom: 20px;">

<div id="informacoes-pessoais" style="max-width: 400px; margin: 0 auto;">

<p>Cidade: Sorocaba </p>

<p>País: Brasil</p>

<p>Interesses: Web Development, Programação, etc.</p>

</div>

</section>


<section style="margin: 20px; text-align: center;">

<h2>Habilidades</h2>

<ul style="list-style: none; padding: 0;">

<li>Linguagens: Python, HTML, CSS, JavaScript</li>

<li>Ferramentas: Git, VS Code</li>

</ul>

</section>


<section style="margin: 20px; text-align: center;">

<h2>Projeto Recente</h2>

<p>Trabalhando em um site pessoal para mostrar meu portfólio.</p>

</section>


<footer style="text-align: center; margin-top: 20px;">

<a href="https://www.linkedin.com/in/andersonsalata/" target="_blank" style="margin: 0 10px; color: #3498db; text-decoration: none;">LinkedIn</a>

</footer>

</body>

</html>

"""
# Exibindo a página HTML

HTML(html_code)

"""##U4_A2"""

!pip install kivymd

from kivy.lang import Builder

from kivy.uix.boxlayout import BoxLayout

from kivy.uix.gridlayout import GridLayout

from kivymd.app import MDApp

from kivymd.uix.button import MDRaisedButton

from kivymd.uix.textfield import MDTextField

from kivy.metrics import dp

KV = """

<CalculatorApp>:

orientation: 'vertical'

MDTextField:

id: input_field

hint_text: "Insira um número"

helper_text_mode: "on_focus"

input_filter: "float"

GridLayout:

cols: 4

spacing: dp(10)

MDRaisedButton:

text: "1"

on_press: app.on_number_press(1)

MDRaisedButton:

text: "2"

on_press: app.on_number_press(2)

MDRaisedButton:

text: "3"

on_press: app.on_number_press(3)

MDRaisedButton:

text: "+"

on_press: app.on_operator_press("+")

MDRaisedButton:

text: "4"

on_press: app.on_number_press(4)

MDRaisedButton:

text: "5"

on_press: app.on_number_press(5)

MDRaisedButton:

text: "6"

on_press: app.on_number_press(6)

MDRaisedButton:

text: "-"

on_press: app.on_operator_press("-")

MDRaisedButton:

text: "7"

on_press: app.on_number_press(7)

MDRaisedButton:

text: "8"

on_press: app.on_number_press(8)

MDRaisedButton:

text: "9"

on_press: app.on_number_press(9)

MDRaisedButton:

text: "*"

on_press: app.on_operator_press("*")

MDRaisedButton:

text: "C"

on_press: app.clear_input()

MDRaisedButton:

text: "0"

on_press: app.on_number_press(0)

MDRaisedButton:

text: "="

on_press: app.calculate_result()

MDRaisedButton:

text: "/"

on_press: app.on_operator_press("/")

"""

class CalculatorApp(BoxLayout):

def on_number_press(self, number):

current_text = self.ids.input_field.text

new_text = f{current_text}{number}

self.ids.input_field.text = new_text

def on_operator_press(self, operator):

current_text = self.ids.input_field.text

new_text = f{current_text} {operator} "

self.ids.input_field.text = new_text

def clear_input(self):

self.ids.input_field.text =

def calculate_result(self):

try:

result = eval(self.ids.input_field.text)

self.ids.input_field.text = str(result)

except Exception as e:

self.ids.input_field.text =

class CalculatorMDApp(MDApp):

def build(self):

return CalculatorApp()

def on_number_press(self, number):

self.root.on_number_press(number)

def on_operator_press(self, operator):

self.root.on_operator_press(operator)

def clear_input(self):

self.root.clear_input()

def calculate_result(self):

self.root.calculate_result()

if __name__ == :

Builder.load_string(KV)

CalculatorMDApp().run()

"""##U4_A3

A historia começa assim...

imagine que você foi contratado por uma fintech chamada PayPython.

Sua primeira missão: criar a função que calcula o total de uma compra no app.

Parece simples. Mas seu chefe avisa:

     "Aqui a gente não sobe código sem teste. Se quebrar em predução, é prejuizo real."

Você vai aprender *3 ferramentas de teste* para garantir que seu código funcine antes de ir ao ar.
===============================================================================================
A função que você criou
Sua tarefa foi criar uma função que soma os valores de uma lista de compras.
Você escreveu isso:
"""

#A função da PayPython - calcula o total de uma lista de compras
def calcular_total(valores):
    return sum(valores)

#Testando manualmente...
compra = [29.90, 15.00, 5.50]
print(f"Total da compra: R$ {calcular_total(compra):.2f}")

"""Funcionou! Mas... e se alguém passar uma lista vazia? E se passar valores negativos?

*Testar na mão não escala.* É aqui que entram as ferramentas do teste.


---

# 🔴 Fase 1 - Assertions: o guarda de segurança

A `assert` é como um **guarda na porta** do seu código.
Ela verifica uma condição e, se for falsa, **para tudo imediatamente** com uma mensagem de erro.

```
assert <condição>, "mensagem se falhar"
```

Use quando quiser **checar suposições críticas** durante o desenvolvimento.
"""

#=============================================
#FASE 1 - Assertions
#=============================================
def calcular_total(valores):
    # Guarda 1: a lista não pode ser None
    assert valores is not None, "❌ A lista de valores não pode ser None!"
    # Guarda 2: nenhum valor pode ser negativo
    assert all(v >= 0 for v in valores), "❌ Valores negativos não são permitidos!"
    return sum(valores)

# ✅ Caso válido - passa sem erro
print("Teste 1:", calcular_total([29.90, 15.00, 5.50]))

# ✅ Lista vazia - também válido (total - zero)
print("Teste 2:", calcular_total([]))

# ✅ Verificando resuldado esperado
assert calcular_total([10, 20, 30]) == 60, "Total errado!"
print("Teste 3: assert passou - resultado correto!")

# ❌ Provocando o erro - valor negativo na lista
# (descomente a linha abaixo para ver o AssertionError)

#calcular_total([10, -5, 20])

"""💡 Quando usar Assertions?
| ✅ Use | ❌ Não use |
| :--- | :--- |
| Checar suposições internas do código | Validar dados de usuário em produção |
| Detectar bugs durante desenvolvimento | Substituir tratamento de exceções (`try/except`) |
| Verificar resultados intermediários | Lógica crítica de negócio |

>  ⚠️ Assertions podem ser desativadas em produção com ```python -0```. Para validação de negócio, use ```raise``` ou ```try/except```.


---

🟠 Fase 2 - Doctest: o teste que vive na documentação
Seu colega de equipe olha o código e pergunta:


> "Mas como eu sei como usar essa função?"

Com **doctest**, você escreve os exemplos de uso **dentro da documentação** da função.
E esses exemplos **viram testes automáticos**. Dois em um! ✅


"""

#====================================================================
# FASE 2 - Doctest
#====================================================================

def calcular_total(valores):
    """
    Calcula o total de uma lista de valores de compra.

    Parâmetros:
        valores (list): lista de números (float ou int)

    Retorna:
        float: soma dos valores

    Exemplos:
    >>> calcular_total([10, 20, 30])
    60
    >>> calcular_total([29.90, 15.00, 5.50])
    50.4
    >>> calcular_total([])
    0
    """
    return sum(valores)

#Rodando os doctests - compara a saída real com os exemplos acima
import doctest
resultado = doctest.testmod(verbose=True)
print(f"\n✅ {resultado.attempted} testes rodados, {resultado.failed} falharam.")

"""💡 Como o Doctest funciona?
```
>>> calcular_total([10, 20, 30])   <- chama a função
60                                 <- resultado esperado
```
o módulo `doctest` lê a docstring, executada cada `>>>` e compara com a linha de baixo.
Se bater - ✅ passou. Se não bater - ❌ falhou.
> 💬 **Vantagem**: a documentação e os testes nunca ficam desatualizados entre si!
---

🟢 Fase 3 - Unittest: o teste profissional
O projeto cresceu. Agora a `calcular_total` é usada em **pagamentos, relatórios e reembolsos.**
> "Precisamos de uma suíte de testes organizada, que rode automático no CI/CD."

É hora do **unittest** - o framework de testes mais robustos da biblioteca padrão do Python.

"""

#===============================================================================
#FASE 3 - Unittest
#===============================================================================

import unittest

def calcular_total(valores):
    return sum(valores)

class TestCaclularTotal(unittest.TestCase):
    """Suíte de testes da função calcular_total - PayPython."""

    def test_compra_normal(self):
        """Soma de valores positivos comuns."""
        self.assertEqual(calcular_total([10, 20, 30]), 60)

    def test_lista_vazia(self):
        """Lista sem itens deve retornar zero."""
        self.assertEqual(calcular_total([]), 0)

    def test_valores_decimais(self):
        """Soma com valores em reais (float)."""
        self.assertAlmostEqual(calcular_total([29.90, 15.00, 5.50]), 50.40, places=2)

    def test_um_item(self):
        """Lista com um único item retorna ele mesmo."""
        self.assertEqual(calcular_total([99]), 99)

    def test_valores_negativos(self):
        """Reembolso: valores negativos cancelam positivos."""
        self.assertEqual(calcular_total([-10, 50]), 40)

#Roda os testes no Jupytar/Colab
unittest.main(argv=[''], exit=False, verbosity=2)

"""💡Anatomia do Unittest

```
class TestCalcularTotal(unittest.TestCase):     #herda TestCase
    def test_xxx(self):                         #todo método começa com test_
        self.assertEqual(resultado, esperado)   # assertiva de comparação
```

### Principais assertivas:

| Método | Verifica |
| :--- | :--- |
| `assertEqual(a, b)` | `a == b` |
| `assertNotEqual(a, b)` | `a != b` |
| `assertTrue(x)` | `x` é verdadeiro |
| `assertFalse(x)` | `x` é falso |
| `assertAlmostEqual(a, b)` | floats aproximadamente iguais |
| `assertRaises(Erro, func)` | função lança o erro esperado |

---

### 🏁 Comparando as 3 abordagens

| | Assert | Doctest | Unittest |
| :--- | :--- | :--- | :--- |
| **Facilidade** | ⭐⭐⭐ | ⭐⭐ | ⭐ |
| **Organização** | baixa | média | alta |
| **Indicado para** | checar suposições | exemplos na doc | projetos sérios |
| **Relatório de erros** | básico | médio | completo |
| **Integração CI/CD** | ❌ | ⚠️ | ✅ |

🎯 Desafio final
A PayPython quer uma nova função: `aplicar_desconto(total, percentual)`.

**Regras de negócio:**



*   Desconto de 10% em `100.00` --> resultado `90.00`
*   Desconto de 0% não altera o valor
*   Desconto não pode ser maior que 100%


"""

#=================================================================
#DESAFIO - Implemente  e teste a função aplicar_desconto
#=================================================================

def aplicar_desconto(total, percentual):
  """
  Aplica um desconto percentual ao total.

  >>> aplicar_desconto(100, 10)
  90.0
  >>> aplicar_desconto(200, 0)
  200.0
  """
  # TODO: implemente aqui!
  pass


# Teste 1 - Assert
#assert aplicar_desconto(100, 10) == 90.0

# Teste 2 - Doctest
#import doctest; doctest.testmod(verbose=True)

# Teste 3 - Unittest (crie sua classe abaixo!)
print("Complete o desafio acima!")

"""✅ Resumo da aula

Você aprendeu **3 formas de testar código Python** usando a história da PayPython:


*   `assert`--> guarda rátpido, checa suposições durante o desenvolvimento
*   `doctest`--> exemplos na documentação que viram testes automáticos
*   `unittest`--> suite organizada em classes, ideal para projetos reais

> 💬Código sem teste é como um avião sem revisão - pode funcionar, mas você não sabe até ser tarde demais.


---

📚 Referências


*   Documentação oficial `unittest`: https://docs.python.org/3/library/unittest.html
*   BANIN, S. L. Python 3 - Conceitos e Aplicações. Érica, 2018.
*    Barry, Paul. Use a Cabeça! Python. Alta Books, 2018.

#A4_U4
"""

## 1. Treinamento SUPERVISIONADO - regressão linear simples (y = 2x)
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import matplotlib.pyplot as plt

## Dados rotulados (entrada + saída esperada)
x_train = tf.constant([[1.0], [2.0], [3.0], [4.0]])
y_train = tf.constant([[2.0], [4.0], [6.0], [8.0]])

model = Sequential()
model.add(Dense(units=1, input_shape=(1,)))
model.compile(optimizer='sgd', loss='mean_squared_error')
history = model.fit(x_train, y_train, epochs=1000, verbose=0)

## Previsão para um valor novo
x_new = tf.constant([[5.0]])
prediction = model.predict (x_new, verbose=0)
print(f"Predição para x=5: {prediction[0][0]:.2f} (esperando:10)")

## Curva de aprendizado
plt.plot(history.history['loss'])
plt.title('Loss ao longo do treinamento')
plt.xlabel('Epoch'); plt.ylabel('Loss')
plt.show()

## 2. Treinamento NÃO SUPERVISIONADO - autoencoder mínimo
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model

## Dados sem rótulo (só X)
x_unsupervised = tf.constant([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [4.0, 5.0]])

## Autoencoder: encode comprime para 1 dimensão; decode reconstrói para 2
input_layer = Input(shape=(2,))
encoded = Dense(units=1)(input_layer)
decoded = Dense(units=2)(encoded)
autoencoder = Model(inputs=input_layer, outputs=decoded)
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

## Treina tentando reconstruir a própria entrada
autoencoder.fit(x_unsupervised, x_unsupervised, epochs=1000, verbose=0)

prediction = autoencoder.predict(x_unsupervised, verbose=0)
print("Original:  ", x_unsupervised.numpy())
print("Reconstruído:", prediction)

## 3. Treinamento POR REFORÇO - conceito + esboço de código
## Atenção. Requer a lib gym/gymnasium (pode dar problema no Colab)
## Aqui vamos só ver a ESTRUTURA típica de um agente.

codigo_reforco = '''
import tensorflow as tf
import gym

env = gym.make('CartPole-v1')

# Rede neural simples como agente
model = tf.keras.Sequential([
    tf.keras.layers.Dense(24, activation='relu',
                          input_chape=(env.observation_space.shape[0],)),
    tf.keras.layers.Dense(env.action_space.n, activation='linear')
])
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss='mse')

# Loop por episódio: o agente age, recebe recompensa, aprende
for episode in range(1000):
  state = env.reset()
  done = False
  while not done:
      action = env.action_space.sample()
      next_state, reward, done, _ = env.step(action)
      # ...ajustar pesos do modelo com base na recompensa
      state = next_state
'''
print(codigo_reforco)

"""##ENCERRAMENTO UNIDADE 4

#🏪 MinhaLoja v4 - Encerramento da Unidade 4

Linguagem de Programação • Aplicações com Python

---

🎬 A história até aqui...
Ao longo da Unidade 4, acompanhamos a evolução da **MinhaLoja**:
| Versão | Aula | O que evoluiu |
| :--- | :--- | :--- |
| **v1** | Aula 1 — Funções e Lambdas | PDV com funções, desconto e lambda |
| **v2** | Aula 2 — Orientação a Objetos | Catálogo com classe `Produto` |
| **v3** | Aula 3 — Banco de Dados + Análise | Vendas em SQLite, Pandas e 4 gráficos |
| **v4** | Agora — Machine Learning | Previsão de vendas para o próximo mês! |
---
Hoje a MinhaLoja ganha **inteligência**: ela vai usar o histórico de vendas para **prever o futuro**. 🔮

---

# 🧩 Parte 1 — Relembrar para avançar

Antes de entrar no Machine Learning, vamos rever rapidamente os pilares das aulas anteriores, porque o encerramento **usa todos eles juntos**.

Aula 1 — Funções e Lambdas
"""

#================================================================#
#REVISÃO - Aula 1: Funções definidas pelo usuário + Lambda       #
#================================================================#

class Produto:
    def __init__(self, nome, preco, categoria, estoque):
        self.nome       =nome
        self.preco      =preco
        self.categoria  =categoria
        self.estoque    =estoque

    def __str__(self):
      return (f"{self.nome} | R$ {self.preco:.2f} | "
              f"Categoria: {self.categoria} | Estoque:  {self.estoque}")

    def aplicar_desconto(self, percentual):
        assert 0 <= percentual <= 100, "❌ O desconto deve ser entre 0 e 100%!"
        self.preco = self.preco - (self.preco * (percentual / 100))

catalogo = [
    Produto("Notebook",        3500.00, "Informática",     12),
    Produto("Smartphone",      2200.00, "Informática",     18),
    Produto("Cafeteira",       350.00, "Eletrodoméstico",   7),
    Produto("Geladeira",       2900.00, "Eletrodoméstico",  4),
    Produto("Fone Bluetooth",  180.00, "Acessório",        30),
]

print("Catálogo da MinhaLoja:")
for p in catalogo:
    print(" ", p)
print("✅ Orientação a Objetos: Ok")

"""#Aula 3 — Banco de Dados + Análise com Pandas"""

#================================================================#
#REVISÃO — Aula 3: SQLite + Pandas + Gráficos                    #
#================================================================#

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

# Banco de dados em memória (sem arquivo em disco)
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

cursor.execute("""
    CREATE TABLE IF NOT EXISTS vendas(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        data TEXT,
        produto TEXT,
        categoria TEXT,
        quantidade INTEGER,
        valor_unitario REAL
    )
""")

vendas_exemplo = [
    ('2024-01-15', 'Notebook',       'Informática',     1, 3500.00),
    ('2024-01-20', 'Cafeteira',      'Eletrodoméstico', 2,  350.00),
    ('2024-01-30', 'Fone Bluetooth', 'Acessório',       4,  180.00),
    ('2024-02-05', 'Smartphone',     'Informática',     1, 2200.00),
    ('2024-02-18', 'Fone Bluetooth', 'Acessório',       3,  180.00),
    ('2024-02-25', 'Notebook',       'Informática',     2, 3500.00),
    ('2024-03-10', 'Geladeira',      'Eletrodoméstico', 1, 2900.00),
    ('2024-03-22', 'Fone Bluetooth', 'Acessório',       5,  180.00),
    ('2024-03-28', 'Cafeteira',      'Eletrodoméstico', 1,  350.00),
    ('2024-04-02', 'Smartphone',     'Informática',     2, 2200.00),
    ('2024-04-19', 'Geladeira',      'Eletrodoméstico', 1, 2900.00),
    ('2024-04-25', 'Notebook',       'Informática',     1, 3500.00),
    ('2024-05-03', 'Cafeteira',      'Eletrodoméstico', 3,  350.00),
    ('2024-05-15', 'Smartphone',     'Informática',     2, 2200.00),
    ('2024-05-28', 'Fone Bluetooth', 'Acessório',       6,  180.00),
    ('2024-06-10', 'Geladeira',      'Eletrodoméstico', 2, 2900.00),
    ('2024-06-20', 'Notebook',       'Informática',     3, 3500.00),
    ('2024-06-30', 'Smartphone',     'Informática',     1, 2200.00),
]

cursor.executemany(
    "INSERT INTO vendas (data, produto, categoria, quantidade, valor_unitario) VALUES (?, ?, ?, ?, ?)",
    vendas_exemplo
)
conn.commit()

#Lendo com Pandas
df = pd.read_sql("SELECT * FROM vendas", conn)
df['total']    = df['quantidade']  * df['valor_unitario']
df['data']     = pd.to_datetime(df['data'])
df['mes']      = df['data'].dt.month
df['mes_nome'] = df['data'].dt.strftime('%b')

print(f"✅ Banco carregado: {len(df)} vendas  | Faturamento total: R$ {df['total'].sum():,.2f}")

"""#🤖 Parte 2 — Aula 4 em ação: Machine Learning no PDV!

A MinhaLoja tem 6 meses de histórico. O dono quer saber:
> *"Quanto vou faturar em julho? Preciso saber antes de fechar o pedido de estoque."*

Vamos usar **aprendizado supervisionado com TensorFlow** para responder isso.

#Por que Supervisionado?

Porque temos **dados com respostas conhecidas** (mês → faturamento real).
O modelo aprende esse padrão e extrapola para meses futuros.
"""

#================================================================#
# MACHINE LEARNING — Preparação dos dados                        #
#================================================================#

import numpy as np
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

# Faturamento mensal extraído do banco (Pandas + SQL)
fat_mes = (df.groupby('mes')['total']
              .sum()
              .reset_index()
              .sort_values('mes'))

print("Faturamento mensal da MinhaLoja:")
for _, row in fat_mes.iterrows():
  print(f"  Mês {int(row['mes'])}: R$ {row['total']:,.2f}")

x = fat_mes[['mes']].values.astype(float)
y = fat_mes[['total']].values.astype(float)

# Normalização — redes neurais aprendem melhor com valores entre 0 e 1
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

x_s = scaler_x.fit_transform(x)
y_s = scaler_y.fit_transform(y)

print(f"\n✅ Dados normalizados e prontos para o modelo.")

#================================================================#
# MACHINE LEARNING — Construção e treino do modelo               #
#================================================================#

# Modelo com 2 camadas — simples, mas suficiente para a tendência
modelo  = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(16, activation='relu'),    #camada escondida
    tf.keras.layers.Dense(1)                        #saída: faturamento
])

modelo.compile(optimizer='adam', loss='mean_squared_error')

# Treinamento com todos os 6 meses disponíveis
history = modelo.fit(x_s, y_s, epochs=1000, verbose=0)

print(f"✅ Modelo treinado! Loss final: {history.history['loss'][-1]:.6f}")

#Visualizando a convergência do treino
plt.figure(figsize=(7, 3))
plt.plot(history.history['loss'], color='steelblue')
plt.title('📉 Erro diminuindo durante o treinamento')
plt.xlabel('Época')
plt.ylabel('Loss (MSE)')
plt.tight_layout()
plt.show()

from inspect import ClosureVars
from IPython.terminal.shortcuts import previous_history_or_previous_completion
#================================================================#
# MACHINE LEARNING — Previsão dos próximos 3 meses               #
#================================================================#

# Previsão para meses 7, 8 e 9 (julho, agosto, setembro)
meses_futuros = np.array([[7], [8], [9]], dtype=float)
meses_futuros_s = scaler_x.transform(meses_futuros)
prev_s  = modelo.predict(meses_futuros_s, verbose=0)
previsoes = scaler_y.inverse_transform(prev_s).ravel()

nomes_meses = {1:'Jan', 2:'Fev', 3:'Mar', 4:'Abr', 5:'Mai', 6:'Jun',
               7:'Jul', 8:'Ago', 9:'Set'}

print("🔮 Previsão de faturamento — MinhaLoja:")
for mes, prev in zip([7, 8, 9], previsoes):
    print(f"  {nomes_meses[mes]}: R$ {prev:,.2f}")

# Gráfico final com histórico + previsão
meses_hist  = fat_mes['mes'].values
fat_hist     = fat_mes['total'].values

# Curva completa do modelo (meses 1 a 9)
todos_meses_s = scaler_x.transform(np.arange(1, 10).reshape(-1, 1))
curva_s = modelo.predict(todos_meses_s, verbose=0)
curva = scaler_y.inverse_transform(curva_s).ravel()

plt.figure(figsize=(10, 4))
plt.scatter(meses_hist, fat_hist, color='steelblue', zorder=5,
            s=80, label='Faturamento real')
plt.plot(np.arange(1, 7), curva[:6], color='steelblue',
         linewidth=2, label='Tendência aprendida')
plt.plot(np.arange(6, 10), curva[5:], color='tomato',
         linewidth=2, linestyle='--', label='Previsão (ML)')
plt.scatter([7, 8, 9], previsoes, color='tomato', marker='*',
            s=200, zorder=6, label='Meses previstos')

# Anotações nos pontos previstos
for mes, prev in zip([7, 8, 9], previsoes):
    plt.annotate(f"R$ {prev:,.0f}",
                 xy=(mes, prev), xytext=(mes + 0.1, prev + 200),
                 fontsize=9, color='tomato')

plt.axvline(x=6.5, color='gray', linestyle=':', alpha=0.6, label='Hoje')
plt.xticks(range(1, 10), [nomes_meses[m] for m in range(1, 10)])
plt.title('🛒 MinhaLoja v4 — Histórico + Previsão de Faturamento (ML)', fontsize=12)
plt.ylabel('Faturamento(R$)')
plt.legend()
plt.tight_layout()
plt.show

"""#🧪 PARTE 3 — Testando nossa previsão (Revisão Aula 3 da U4)

Antes de confiar na previsão, precisamos **testar o modelo**.
Aplicamos os conceitos da aula de testes:`assert` e métricas de avaliação.
"""

#================================================================#
# TESTES — Validando o modelo de previsão                        #
#================================================================#

# Reconstrói a previsão para os meses históricos
pred_hist_s = modelo.predict(x_s, verbose=0)
pred_hist   = scaler_y.inverse_transform(pred_hist_s).ravel()

from sklearn.metrics import mean_squared_error
rmse  = np.sqrt(mean_squared_error(y.ravel(), pred_hist))

print("📊 Avaliação do modelo nos dados históricos:")
for mes, real, prev in zip(meses_hist, fat_hist, pred_hist):
  diff  = abs(real - prev)
  print(f"  {nomes_meses[mes]}: Real R$ {real:,.0f} | Previsto R$ {prev:,.0f} | Diferença R$ {diff:,.0f}")

print(f"\nRMSE (erro médio): R$ {rmse:,.2f}")

# Assert — garante que o modelo tem precisão mínima aceitável
tolerancia = fat_hist.mean() * 0.30   #aceitamos até 30% de erro médio
assert rmse < tolerancia, f"❌ Modelo com erro alto demais: R$ {rmse:,.2f}"
print(f"\n✅ Assert passou — modelo dentro da tolerância de R$ {tolerancia:,.2f}")

"""#🏁 PARTE 4 — A MinhaLoja completa: tudo junto

Veja como os **4 conceitos da unidade** se encaixam num sistema real:
"""

#================================================================#
# RELATÓRIO EXECUTIVO — MinhaLoja v4                             #
# Une: Funções •  OOP • Banco + Pandas  • ML                     #
#================================================================#

def gerar_relatorio_executivo(df, catalogo, previsoes, meses_futuros):
    """Gera o relatório completo da MinhaLoja v4."""

    print("=" * 55)
    print("       🏪 MinhaLoja v4 — Relatório Executivo")
    print("=" * 55)

    # --- Funções (Aula 1)  ---
    print("\n📋 PDV — Última venda do dia:")
    valor_final = arredondar(calcular_desconto(2200.00, 5))
    registrar_venda("Smartphone", valor_final)

    ##Incremento meu
def calcular_comissao(valor_venda, percentual):
    assert percentual is not None, "❌ o percentual não pode ser None!"
    assert 0 <= percentual <= 20, "❌ o percentual deve estar entre 0 e 20!"
    comissao = valor_venda * (percentual / 100)


    # --- OOP (Aula 2)  ---
    print("\n📦 Produto mais caro do catálogo:")
    mais_caro = max(catalogo, key=lambda p: p.preco)
    print(f"  {mais_caro}")

    # --- Banco + Pandas (Aula 3) ---
    print("\n📊 Resumo do histórico (SQL + Pandas):")
    ranking = (df.groupby('produto')['total']
                 .sum()
                 .sort_values(ascending=False))
    for prod, fat in ranking.items():
        print(f"  {prod:<20} R$ {fat:,.2f}")

    # --- Machine Learning (Aula 4) ---
    print("\n🤖 Previsão de faturamento (TensorFlow):")
    for mes, prev in zip(meses_futuros, previsoes):
        print(f"  {nomes_meses[int(mes[0])]}: R$  {prev:,.2f}")

print("\n" + "=" * 55)
print(" MinhaLoja v4 — Python aplicado do PDV ao ML 🚀")
print("=" * 55)

gerar_relatorio_executivo(df, catalogo, previsoes, meses_futuros)

"""##Desafio Final da Unidade 4

Você chegou até aqui — agora é sua vez de expandir a MinhaLoja!

Escolha pelo menos **um** dos desafios abaixo:

---
# DESAFIOS — Escolha um (ou todos) para praticar                 
---
>
 🥉 FÁCIL — Funções (Aula 1)
 Crie uma função `calcular_comissao(valor_venda, percentual)`
 Adicione um assert para garantir que o percentual seja entre 0 e 20%.
>
 🥈 MÉDIO — OOP (Aula 2)
 Adicione um método `aplicar_desconto(percentual)` na classe Produto
 que atualiza o preço do produto diretamente no objeto.
>
 🥇 DIFÍCIL — ML (Aula 4)
 Treine um modelo separado por categoria (Informática, Eletrodoméstico, Acessório)
 e compare as previsões de julho para cada uma.
"""

def calcular_comissao(valor_venda, percentual)
    assert valor_venda is not None, "❌ A lista de valores não pode ser None!"